### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by qttis** [Jityan/sft#1]
Dear author, could you please share a link to the tiered-imagenet-kwon dataset? The original paper link you provided is no longer accessible. Thank you for your excellent work.
![1](https://github.com/user-attachments/assets/8dc172a8-035e-4b8d-b9d5-8ff8bcbcdfd5)

**Comment by Jityan** [comment]
Hi there,

You may get the dataset from here: https://www.dropbox.com/sh/6yd1ygtyc3yd981/AABVeEqzC08YQv4UZk7lNHvya?dl=0

The file need to be used:
1. train_images.npz
2. train_labels.pkl
3. val_images.npz
4. val_labels.pkl
5. test_images.npz
6. test_labels.pkl

Thank you and hope you have a nice day.

**Comment by qttis** [comment]
Thank you for your excellent work.
